"""add author gender

Revision ID: 406e617ae25c
Revises: 5d79dbe6d335
Create Date: 2026-09-01 14:38:25.071502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406e617ae25c'
down_revision: Union[str, Sequence[str], None] = '5d79dbe6d335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    author_gender_enum = sa.Enum(
            'male',
            'female',
            'non_binary',
            'unknown',
            name='author_gender'
        )

    author_gender_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'authors',
        sa.Column(
            'author_gender',
            author_gender_enum,
            nullable=True
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    author_gender_enum = sa.Enum(
        'male',
        'female',
        'non_binary',
        'unknown',
        name='author_gender'
    )

    op.drop_column('authors', 'author_gender')
    author_gender_enum.drop(op.get_bind(), checkfirst=True)